### ISSUE TITLE
Naming functions, variables, constants

### ISSUE THREAD

**Issue by i-gk** [sumudusujith/circles-login#2]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/routesClass.js#L3

A class in `javascript` is available in ES6. But this is not the syntax for it. Since this is containing a object and unlikely to be changed best would be to use a const. 

Appropriate name would be `const ROUTES = {...}`

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/routesClass.js#L1

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/routesClass.js#L10

It's an improvement for code readability to follow the same naming convention. Here the two variables are in two diff formats. One in snake_case and the other is camelCase. You should pick one and continue to stick to it across the codebase when declaring constants.

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/Routes.js#L23-L25

Here in this instance `component={reduxLogin}` and `component={Dashboard}` are in two different naming format. Since these are components best approach would  CamelCase with capital start

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/sagas/sagas.js#L7

The name of this generator function can be better. a function always does something, so the name should ideally explain what the function is doing

I see the `fetchUser` generator function below this page, which is a much better name.

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/sagas/sagas.js#L22

Can do better with the log message. I mean why _ and then <space> ? Its a message so we can stick to spaces

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/redux/reducers/index.js#L8-L13

Maintain a naming convention. Recommended to use camelCase

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/redux/reducers/loginReducer.js#L71

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/redux/reducers/loginReducer.js#L87

Naming of these functions are off. What did you try to mean by `sagaLoginReducer`? Can we think of a better name that actually express the function duty?

**Comment by sumudusujith** [comment]
issues cleared
