### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by i-gk** [sumudusujith/circles-login#3]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/index.js#L19-L29

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/index.js#L9-L12

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/fetch.js#L3-L5

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/fetch.js#L59-L87

https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/App.js#L13-L19

It is always the best practice to remove the unused/commented code. If the commented code is really needed for reference then its better to add a comment stating why the commented code is in place in the codebase.

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/sagas/sagas.js#L9

Here the parameters are passed accessing the object every time. This makes the readability hard. We should destructure the payload only for the required attributes and use them

**Comment by i-gk** [comment]
https://github.com/sumudusujith/circles-login/blob/7e888d4e37611cccf387751348a712e8c5310f88/src/redux/store.js#L7-L12

Remove unnecessary new lines

**Comment by sumudusujith** [comment]
issues cleared
